spring.application.name=maum_on

kakao.client-id=${KAKAO_REST_API_KEY}
kakao.redirect-uri=http://localhost:8080/auth/kakao/callback
kakao.client-secret=${KAKAO_CLIENT_SECRET}

kakao.auth-url=https://kauth.kakao.com
kakao.token-uri=${kakao.auth-url}/oauth/token
kakao.admin-key=${KAKAO_ADMIN_KEY}

kakao.api-url=https://kapi.kakao.com
kakao.user-info-uri=${kakao.api-url}/v2/user/me

jwt.secret=${JWT_SECRET_KEY}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true

cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
cloud.aws.s3.bucket=${AWS_S3_BUCKET}
cloud.aws.region.static=ap-northeast-2
cloud.aws.stack.auto=false

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB